version: '3.1'
services:
  mariadb:
    image: mariadb:10.6
    restart: always
    volumes:
      - mariadb-storage:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  query_data:
    build: ./query_data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  mariadb-storage:
